# Generated by packaging/homebrew/formula.sh in cfmleditor/clif for each
# release. Edit that script, not this file.
class Clif < Formula
  desc "CFML language server and command-line checks (formerly cfmleditor-lsp)"
  homepage "https://github.com/cfmleditor/clif"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/cfmleditor/clif/releases/download/v0.5.2/clif-darwin-arm64.tar.gz"
      sha256 "ce0a0f33a80697638ea1d25a0c007093430403cef88d23e39478ec6f33e69729"
    end
    on_intel do
      url "https://github.com/cfmleditor/clif/releases/download/v0.5.2/clif-darwin-amd64.tar.gz"
      sha256 "b57283a161731507514cd4f6f5626978b54d2d9260ae8f9791d4368d2db19072"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/cfmleditor/clif/releases/download/v0.5.2/clif-linux-arm64.tar.gz"
      sha256 "ddb1be1f0ad97904399791cf5e753f723e8624972c2257cff4863ebda07115b7"
    end
    on_intel do
      url "https://github.com/cfmleditor/clif/releases/download/v0.5.2/clif-linux-amd64.tar.gz"
      sha256 "478315bca9f1d0b7adbace01bb24d2b04dbdc056227fc78ea8c1cec343f37999"
    end
  end

  def install
    bin.install "clif"
    bin.install_symlink "clif" => "cfmleditor-lsp"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/clif version")
    assert_match "usage: clif unresolved", shell_output("#{bin}/clif unresolved --help")
  end
end
