# Generated by packaging/homebrew/formula.sh in cfmleditor/clif for each
# release. Edit that script, not this file.
class Clif < Formula
  desc "CFML language server and command-line checks (formerly cfmleditor-lsp)"
  homepage "https://github.com/cfmleditor/clif"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/cfmleditor/clif/releases/download/v0.5.1/clif-darwin-arm64.tar.gz"
      sha256 "74d38e3ce53f6a4913793e421017e0bd347493ddda6d9bc06400e61d3a4cf3d2"
    end
    on_intel do
      url "https://github.com/cfmleditor/clif/releases/download/v0.5.1/clif-darwin-amd64.tar.gz"
      sha256 "140a1fed1701e446210603fbd702bc5dd6588c30a88a302bd0cc858e31075eb2"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/cfmleditor/clif/releases/download/v0.5.1/clif-linux-arm64.tar.gz"
      sha256 "932d7fc71ad4fce2684b5524e8ce7566f31944b86832d0b5f765ab4a4995fb68"
    end
    on_intel do
      url "https://github.com/cfmleditor/clif/releases/download/v0.5.1/clif-linux-amd64.tar.gz"
      sha256 "0b17e95109aeda3f726b3913c7cb99fb9e57c5a58f87186c434d6e010aec926a"
    end
  end

  def install
    bin.install "clif"
    bin.install_symlink "clif" => "cfmleditor-lsp"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/clif version")
    assert_match "usage: clif unresolved", shell_output("#{bin}/clif unresolved --help")
  end
end
