# Generated by packaging/homebrew/formula.sh in cfmleditor/clif for each
# release. Edit that script, not this file.
class Clif < Formula
  desc "CFML language server and command-line checks (formerly cfmleditor-lsp)"
  homepage "https://github.com/cfmleditor/clif"
  version "0.5.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/cfmleditor/clif/releases/download/v0.5.0/clif-darwin-arm64.tar.gz"
      sha256 "6b2b5888411f56b00ffbd32574ffe2f4dd4fb2ca7c79331fe7fa993dbbd34af3"
    end
    on_intel do
      url "https://github.com/cfmleditor/clif/releases/download/v0.5.0/clif-darwin-amd64.tar.gz"
      sha256 "f1bbe848c204b7ccc6a9f29b8d49cb3e91505499c527bf4970613eefdf4b9d16"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/cfmleditor/clif/releases/download/v0.5.0/clif-linux-arm64.tar.gz"
      sha256 "aed3c949cc088ab425561a42b8726413f718385172dbb46e298a2152d50b2734"
    end
    on_intel do
      url "https://github.com/cfmleditor/clif/releases/download/v0.5.0/clif-linux-amd64.tar.gz"
      sha256 "488d0f3da80ef39bc441e9f935dcaa30184fb41da75cbbf8f205ca1c0d0a6200"
    end
  end

  def install
    bin.install "clif"
    bin.install_symlink "clif" => "cfmleditor-lsp"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/clif version")
    assert_match "usage: clif unresolved", shell_output("#{bin}/clif unresolved --help")
  end
end
